
name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:

  build:
   
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4      
      - name: Build image
        run: docker build -t marthe2025/portfolio .
    
      - name: Push image
        run: |
         docker login -u marthe2025 -p ${{secrets.REGISTRY_PASS}}
         docker push marthe2025/portfolio

        
          
